server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: notification-service
          uri: lb://notification
          predicates:
            - Path=/email/**
        - id: financas-service
          uri: lb://financas
          predicates:
            - Path=/oauth/token**, /empresas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defautZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true