server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: notificationModule
          uri: http://localhost:8081/
          predicates:
            - Path=/email/**
        - id: fintionModule
          uri: http://localhost:8087/
          predicates:
            - Path=/empresas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defautZone: http://localhost:8761/eureka